joy_teleop:
  ros__parameters:
    default:
      type: topic
      interface_type: ackermann_msgs/msg/AckermannDriveStamped
      topic_name: teleop
      axis_mappings:
        drive-speed:
          axis: 3
          scale: -1.0
          offset: 0.0
        drive-steering_angle:
          axis: 1
          scale: -0.35
          offset: 0.0
